/**
 * Auto-generated by 'supabase gen types typescript --local'
 * This file will be overwritten when you run the gen types command.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          job_title: string | null;
          company: string | null;
          assessment_cycle: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          job_title?: string | null;
          company?: string | null;
          assessment_cycle?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          job_title?: string | null;
          company?: string | null;
          assessment_cycle?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      goals: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          specific: string | null;
          measurable: string | null;
          achievable: string | null;
          relevant: string | null;
          time_bound: string | null;
          status: string;
          ai_suggested: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          specific?: string | null;
          measurable?: string | null;
          achievable?: string | null;
          relevant?: string | null;
          time_bound?: string | null;
          status?: string;
          ai_suggested?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string | null;
          specific?: string | null;
          measurable?: string | null;
          achievable?: string | null;
          relevant?: string | null;
          time_bound?: string | null;
          status?: string;
          ai_suggested?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          goal_id: string;
          title: string;
          description: string | null;
          order_index: number;
          status: string;
          blocker_description: string | null;
          due_date: string | null;
          ai_generated: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          goal_id: string;
          title: string;
          description?: string | null;
          order_index: number;
          status?: string;
          blocker_description?: string | null;
          due_date?: string | null;
          ai_generated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          goal_id?: string;
          title?: string;
          description?: string | null;
          order_index?: number;
          status?: string;
          blocker_description?: string | null;
          due_date?: string | null;
          ai_generated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      action_logs: {
        Row: {
          id: string;
          task_id: string;
          user_id: string;
          action_description: string;
          impact_notes: string | null;
          time_spent_minutes: number | null;
          logged_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          task_id: string;
          user_id: string;
          action_description: string;
          impact_notes?: string | null;
          time_spent_minutes?: number | null;
          logged_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          task_id?: string;
          user_id?: string;
          action_description?: string;
          impact_notes?: string | null;
          time_spent_minutes?: number | null;
          logged_at?: string;
          created_at?: string;
        };
      };
      ai_interactions: {
        Row: {
          id: string;
          user_id: string;
          interaction_type: string;
          goal_id: string | null;
          prompt: string;
          response: string;
          tokens_used: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          interaction_type: string;
          goal_id?: string | null;
          prompt: string;
          response: string;
          tokens_used?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          interaction_type?: string;
          goal_id?: string | null;
          prompt?: string;
          response?: string;
          tokens_used?: number | null;
          created_at?: string;
        };
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};
